# Generated by Django 5.0.1 on 2024-01-15 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0002_assignedtasks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='assigned_user',
        ),
    ]
